### ISSUE TITLE
can not superimpose radar data on camera images

### ISSUE THREAD

**Issue by liuyf5231** [AinsteinAI/ainstein_radar#3]
Hi, 
When i use radar_camera_fusion_node, project the radar 3d point to 2d pixel coordinates,
`cam_model_.project3dToPixel`  will return inf .
I have calibrated my monocular camera followed this [site ](http://wiki.ros.org/camera_calibration).
Thanks .

**Comment by nrotella-ainstein** [comment]
Hi, I'm sorry I'm just seeing your issue now. Did you manage to resolve it? I have had this issue with a poorly calibrated camera.
